kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-deployment
spec:
  replicas: 8
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 5225/object_detection
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "0.5"
          requests:
            memory: "512Mi"
            cpu: "0.5"
